version: '3'
services:
  db:
    image: mariadb:latest
    container_name: database-container
    environment:
      MARIADB_DATABASE: testdatabase
      MARIADB_ROOT_PASSWORD: 0105
    ports:
      - "3306:3306"
    restart: always
  backend:
    image: backend:latest
    container_name: backend-container
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL-HOST: db
      PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD:

